service: my-first-serverless-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  stage: dev
  region: eu-north-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /create
          method: post

plugins:
  - serverless-offline
